//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyToolMobile.Service.File.Reader {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="現在庫データ", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 現在庫データ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _名称２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string レセプト電算処理システムコードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 使用期限Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 個別医薬品コードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名と名称２連結Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 在庫数Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 店名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 後発区分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終更新日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 薬価Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 製造会社Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _名称２ {
            get {
                return this._名称２Field;
            }
            set {
                if ((object.ReferenceEquals(this._名称２Field, value) != true)) {
                    this._名称２Field = value;
                    this.RaisePropertyChanged("_名称２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string レセプト電算処理システムコード {
            get {
                return this.レセプト電算処理システムコードField;
            }
            set {
                if ((object.ReferenceEquals(this.レセプト電算処理システムコードField, value) != true)) {
                    this.レセプト電算処理システムコードField = value;
                    this.RaisePropertyChanged("レセプト電算処理システムコード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 使用期限 {
            get {
                return this.使用期限Field;
            }
            set {
                if ((this.使用期限Field.Equals(value) != true)) {
                    this.使用期限Field = value;
                    this.RaisePropertyChanged("使用期限");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 個別医薬品コード {
            get {
                return this.個別医薬品コードField;
            }
            set {
                if ((object.ReferenceEquals(this.個別医薬品コードField, value) != true)) {
                    this.個別医薬品コードField = value;
                    this.RaisePropertyChanged("個別医薬品コード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名 {
            get {
                return this.医薬品名Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名Field, value) != true)) {
                    this.医薬品名Field = value;
                    this.RaisePropertyChanged("医薬品名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名と名称２連結 {
            get {
                return this.医薬品名と名称２連結Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名と名称２連結Field, value) != true)) {
                    this.医薬品名と名称２連結Field = value;
                    this.RaisePropertyChanged("医薬品名と名称２連結");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 在庫数 {
            get {
                return this.在庫数Field;
            }
            set {
                if ((object.ReferenceEquals(this.在庫数Field, value) != true)) {
                    this.在庫数Field = value;
                    this.RaisePropertyChanged("在庫数");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 店名 {
            get {
                return this.店名Field;
            }
            set {
                if ((object.ReferenceEquals(this.店名Field, value) != true)) {
                    this.店名Field = value;
                    this.RaisePropertyChanged("店名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 後発区分 {
            get {
                return this.後発区分Field;
            }
            set {
                if ((object.ReferenceEquals(this.後発区分Field, value) != true)) {
                    this.後発区分Field = value;
                    this.RaisePropertyChanged("後発区分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終更新日時 {
            get {
                return this.最終更新日時Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終更新日時Field, value) != true)) {
                    this.最終更新日時Field = value;
                    this.RaisePropertyChanged("最終更新日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 薬価 {
            get {
                return this.薬価Field;
            }
            set {
                if ((object.ReferenceEquals(this.薬価Field, value) != true)) {
                    this.薬価Field = value;
                    this.RaisePropertyChanged("薬価");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 製造会社 {
            get {
                return this.製造会社Field;
            }
            set {
                if ((object.ReferenceEquals(this.製造会社Field, value) != true)) {
                    this.製造会社Field = value;
                    this.RaisePropertyChanged("製造会社");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="在庫リターンデータセットOf薬局使用量データZYtYGqK_P", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 在庫リターンデータセットOf薬局使用量データZYtYGqK_P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 検索キーワードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PharmacyToolMobile.Service.File.Reader.薬局使用量データ[] 検索結果データlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 検索キーワード {
            get {
                return this.検索キーワードField;
            }
            set {
                if ((object.ReferenceEquals(this.検索キーワードField, value) != true)) {
                    this.検索キーワードField = value;
                    this.RaisePropertyChanged("検索キーワード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PharmacyToolMobile.Service.File.Reader.薬局使用量データ[] 検索結果データlist {
            get {
                return this.検索結果データlistField;
            }
            set {
                if ((object.ReferenceEquals(this.検索結果データlistField, value) != true)) {
                    this.検索結果データlistField = value;
                    this.RaisePropertyChanged("検索結果データlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="薬局使用量データ", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 薬局使用量データ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 使用年月Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 使用量Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名と名称２連結Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 名称２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 商品コードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 店名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終更新日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 薬価Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 使用年月 {
            get {
                return this.使用年月Field;
            }
            set {
                if ((object.ReferenceEquals(this.使用年月Field, value) != true)) {
                    this.使用年月Field = value;
                    this.RaisePropertyChanged("使用年月");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 使用量 {
            get {
                return this.使用量Field;
            }
            set {
                if ((object.ReferenceEquals(this.使用量Field, value) != true)) {
                    this.使用量Field = value;
                    this.RaisePropertyChanged("使用量");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名 {
            get {
                return this.医薬品名Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名Field, value) != true)) {
                    this.医薬品名Field = value;
                    this.RaisePropertyChanged("医薬品名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名と名称２連結 {
            get {
                return this.医薬品名と名称２連結Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名と名称２連結Field, value) != true)) {
                    this.医薬品名と名称２連結Field = value;
                    this.RaisePropertyChanged("医薬品名と名称２連結");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 名称２ {
            get {
                return this.名称２Field;
            }
            set {
                if ((object.ReferenceEquals(this.名称２Field, value) != true)) {
                    this.名称２Field = value;
                    this.RaisePropertyChanged("名称２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 商品コード {
            get {
                return this.商品コードField;
            }
            set {
                if ((object.ReferenceEquals(this.商品コードField, value) != true)) {
                    this.商品コードField = value;
                    this.RaisePropertyChanged("商品コード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 店名 {
            get {
                return this.店名Field;
            }
            set {
                if ((object.ReferenceEquals(this.店名Field, value) != true)) {
                    this.店名Field = value;
                    this.RaisePropertyChanged("店名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終更新日時 {
            get {
                return this.最終更新日時Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終更新日時Field, value) != true)) {
                    this.最終更新日時Field = value;
                    this.RaisePropertyChanged("最終更新日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 薬価 {
            get {
                return this.薬価Field;
            }
            set {
                if ((object.ReferenceEquals(this.薬価Field, value) != true)) {
                    this.薬価Field = value;
                    this.RaisePropertyChanged("薬価");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="在庫リターンデータセットOf不動品データZYtYGqK_P", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 在庫リターンデータセットOf不動品データZYtYGqK_P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 検索キーワードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PharmacyToolMobile.Service.File.Reader.不動品データ[] 検索結果データlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 検索キーワード {
            get {
                return this.検索キーワードField;
            }
            set {
                if ((object.ReferenceEquals(this.検索キーワードField, value) != true)) {
                    this.検索キーワードField = value;
                    this.RaisePropertyChanged("検索キーワード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PharmacyToolMobile.Service.File.Reader.不動品データ[] 検索結果データlist {
            get {
                return this.検索結果データlistField;
            }
            set {
                if ((object.ReferenceEquals(this.検索結果データlistField, value) != true)) {
                    this.検索結果データlistField = value;
                    this.RaisePropertyChanged("検索結果データlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="不動品データ", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 不動品データ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string レセプト電算処理システムコードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 一包単位量Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 使用期限Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 個別医薬品コードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 医薬品名と名称２連結Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 名称２Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 在庫数Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 店名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 最終更新日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double 薬価Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string レセプト電算処理システムコード {
            get {
                return this.レセプト電算処理システムコードField;
            }
            set {
                if ((object.ReferenceEquals(this.レセプト電算処理システムコードField, value) != true)) {
                    this.レセプト電算処理システムコードField = value;
                    this.RaisePropertyChanged("レセプト電算処理システムコード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 一包単位量 {
            get {
                return this.一包単位量Field;
            }
            set {
                if ((object.ReferenceEquals(this.一包単位量Field, value) != true)) {
                    this.一包単位量Field = value;
                    this.RaisePropertyChanged("一包単位量");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 使用期限 {
            get {
                return this.使用期限Field;
            }
            set {
                if ((this.使用期限Field.Equals(value) != true)) {
                    this.使用期限Field = value;
                    this.RaisePropertyChanged("使用期限");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 個別医薬品コード {
            get {
                return this.個別医薬品コードField;
            }
            set {
                if ((object.ReferenceEquals(this.個別医薬品コードField, value) != true)) {
                    this.個別医薬品コードField = value;
                    this.RaisePropertyChanged("個別医薬品コード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名 {
            get {
                return this.医薬品名Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名Field, value) != true)) {
                    this.医薬品名Field = value;
                    this.RaisePropertyChanged("医薬品名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 医薬品名と名称２連結 {
            get {
                return this.医薬品名と名称２連結Field;
            }
            set {
                if ((object.ReferenceEquals(this.医薬品名と名称２連結Field, value) != true)) {
                    this.医薬品名と名称２連結Field = value;
                    this.RaisePropertyChanged("医薬品名と名称２連結");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 名称２ {
            get {
                return this.名称２Field;
            }
            set {
                if ((object.ReferenceEquals(this.名称２Field, value) != true)) {
                    this.名称２Field = value;
                    this.RaisePropertyChanged("名称２");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 在庫数 {
            get {
                return this.在庫数Field;
            }
            set {
                if ((object.ReferenceEquals(this.在庫数Field, value) != true)) {
                    this.在庫数Field = value;
                    this.RaisePropertyChanged("在庫数");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 店名 {
            get {
                return this.店名Field;
            }
            set {
                if ((object.ReferenceEquals(this.店名Field, value) != true)) {
                    this.店名Field = value;
                    this.RaisePropertyChanged("店名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 最終更新日時 {
            get {
                return this.最終更新日時Field;
            }
            set {
                if ((object.ReferenceEquals(this.最終更新日時Field, value) != true)) {
                    this.最終更新日時Field = value;
                    this.RaisePropertyChanged("最終更新日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double 薬価 {
            get {
                return this.薬価Field;
            }
            set {
                if ((this.薬価Field.Equals(value) != true)) {
                    this.薬価Field = value;
                    this.RaisePropertyChanged("薬価");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="在庫リターンデータセットOf現在庫データZYtYGqK_P", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 在庫リターンデータセットOf現在庫データZYtYGqK_P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 検索キーワードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PharmacyToolMobile.Service.File.Reader.現在庫データ[] 検索結果データlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 検索キーワード {
            get {
                return this.検索キーワードField;
            }
            set {
                if ((object.ReferenceEquals(this.検索キーワードField, value) != true)) {
                    this.検索キーワードField = value;
                    this.RaisePropertyChanged("検索キーワード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PharmacyToolMobile.Service.File.Reader.現在庫データ[] 検索結果データlist {
            get {
                return this.検索結果データlistField;
            }
            set {
                if ((object.ReferenceEquals(this.検索結果データlistField, value) != true)) {
                    this.検索結果データlistField = value;
                    this.RaisePropertyChanged("検索結果データlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="掲示板リターンデータセット", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 掲示板リターンデータセット : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool キーワード検索結果かField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int メイン記事数Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 作成グループNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<PharmacyToolMobile.Service.File.Reader.投稿Entity, PharmacyToolMobile.Service.File.Reader.返信Entity[]>[] 掲示板データField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 検索したキーワードField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 記事取得成功かField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool キーワード検索結果か {
            get {
                return this.キーワード検索結果かField;
            }
            set {
                if ((this.キーワード検索結果かField.Equals(value) != true)) {
                    this.キーワード検索結果かField = value;
                    this.RaisePropertyChanged("キーワード検索結果か");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int メイン記事数 {
            get {
                return this.メイン記事数Field;
            }
            set {
                if ((this.メイン記事数Field.Equals(value) != true)) {
                    this.メイン記事数Field = value;
                    this.RaisePropertyChanged("メイン記事数");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 作成グループNo {
            get {
                return this.作成グループNoField;
            }
            set {
                if ((this.作成グループNoField.Equals(value) != true)) {
                    this.作成グループNoField = value;
                    this.RaisePropertyChanged("作成グループNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<PharmacyToolMobile.Service.File.Reader.投稿Entity, PharmacyToolMobile.Service.File.Reader.返信Entity[]>[] 掲示板データ {
            get {
                return this.掲示板データField;
            }
            set {
                if ((object.ReferenceEquals(this.掲示板データField, value) != true)) {
                    this.掲示板データField = value;
                    this.RaisePropertyChanged("掲示板データ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 検索したキーワード {
            get {
                return this.検索したキーワードField;
            }
            set {
                if ((object.ReferenceEquals(this.検索したキーワードField, value) != true)) {
                    this.検索したキーワードField = value;
                    this.RaisePropertyChanged("検索したキーワード");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 記事取得成功か {
            get {
                return this.記事取得成功かField;
            }
            set {
                if ((this.記事取得成功かField.Equals(value) != true)) {
                    this.記事取得成功かField = value;
                    this.RaisePropertyChanged("記事取得成功か");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="投稿Entity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 投稿Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomepageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string カテゴリ名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 投稿日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 投稿者名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 文字色Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 暗証キーField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] 添付ファイルlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 記事Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomepageUrl {
            get {
                return this.HomepageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HomepageUrlField, value) != true)) {
                    this.HomepageUrlField = value;
                    this.RaisePropertyChanged("HomepageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string カテゴリ名 {
            get {
                return this.カテゴリ名Field;
            }
            set {
                if ((object.ReferenceEquals(this.カテゴリ名Field, value) != true)) {
                    this.カテゴリ名Field = value;
                    this.RaisePropertyChanged("カテゴリ名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 投稿日 {
            get {
                return this.投稿日Field;
            }
            set {
                if ((object.ReferenceEquals(this.投稿日Field, value) != true)) {
                    this.投稿日Field = value;
                    this.RaisePropertyChanged("投稿日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 投稿者名 {
            get {
                return this.投稿者名Field;
            }
            set {
                if ((object.ReferenceEquals(this.投稿者名Field, value) != true)) {
                    this.投稿者名Field = value;
                    this.RaisePropertyChanged("投稿者名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 文字色 {
            get {
                return this.文字色Field;
            }
            set {
                if ((object.ReferenceEquals(this.文字色Field, value) != true)) {
                    this.文字色Field = value;
                    this.RaisePropertyChanged("文字色");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 暗証キー {
            get {
                return this.暗証キーField;
            }
            set {
                if ((object.ReferenceEquals(this.暗証キーField, value) != true)) {
                    this.暗証キーField = value;
                    this.RaisePropertyChanged("暗証キー");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] 添付ファイルlist {
            get {
                return this.添付ファイルlistField;
            }
            set {
                if ((object.ReferenceEquals(this.添付ファイルlistField, value) != true)) {
                    this.添付ファイルlistField = value;
                    this.RaisePropertyChanged("添付ファイルlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 記事 {
            get {
                return this.記事Field;
            }
            set {
                if ((object.ReferenceEquals(this.記事Field, value) != true)) {
                    this.記事Field = value;
                    this.RaisePropertyChanged("記事");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="返信Entity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 返信Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomepageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string カテゴリ名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 投稿日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 投稿者名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 文字色Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] 添付ファイルlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 記事Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomepageUrl {
            get {
                return this.HomepageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HomepageUrlField, value) != true)) {
                    this.HomepageUrlField = value;
                    this.RaisePropertyChanged("HomepageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string カテゴリ名 {
            get {
                return this.カテゴリ名Field;
            }
            set {
                if ((object.ReferenceEquals(this.カテゴリ名Field, value) != true)) {
                    this.カテゴリ名Field = value;
                    this.RaisePropertyChanged("カテゴリ名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 投稿日 {
            get {
                return this.投稿日Field;
            }
            set {
                if ((object.ReferenceEquals(this.投稿日Field, value) != true)) {
                    this.投稿日Field = value;
                    this.RaisePropertyChanged("投稿日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 投稿者名 {
            get {
                return this.投稿者名Field;
            }
            set {
                if ((object.ReferenceEquals(this.投稿者名Field, value) != true)) {
                    this.投稿者名Field = value;
                    this.RaisePropertyChanged("投稿者名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 文字色 {
            get {
                return this.文字色Field;
            }
            set {
                if ((object.ReferenceEquals(this.文字色Field, value) != true)) {
                    this.文字色Field = value;
                    this.RaisePropertyChanged("文字色");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] 添付ファイルlist {
            get {
                return this.添付ファイルlistField;
            }
            set {
                if ((object.ReferenceEquals(this.添付ファイルlistField, value) != true)) {
                    this.添付ファイルlistField = value;
                    this.RaisePropertyChanged("添付ファイルlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 記事 {
            get {
                return this.記事Field;
            }
            set {
                if ((object.ReferenceEquals(this.記事Field, value) != true)) {
                    this.記事Field = value;
                    this.RaisePropertyChanged("記事");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="掲示板記事修正確認Entity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 掲示板記事修正確認Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 暗証キーチェック成功Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PharmacyToolMobile.Service.File.Reader.投稿Entity 記事データField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 暗証キーチェック成功 {
            get {
                return this.暗証キーチェック成功Field;
            }
            set {
                if ((this.暗証キーチェック成功Field.Equals(value) != true)) {
                    this.暗証キーチェック成功Field = value;
                    this.RaisePropertyChanged("暗証キーチェック成功");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PharmacyToolMobile.Service.File.Reader.投稿Entity 記事データ {
            get {
                return this.記事データField;
            }
            set {
                if ((object.ReferenceEquals(this.記事データField, value) != true)) {
                    this.記事データField = value;
                    this.RaisePropertyChanged("記事データ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThreadTitlesEntity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class ThreadTitlesEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime スレッド作成日Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string スレッド名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 画像パスField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime スレッド作成日 {
            get {
                return this.スレッド作成日Field;
            }
            set {
                if ((this.スレッド作成日Field.Equals(value) != true)) {
                    this.スレッド作成日Field = value;
                    this.RaisePropertyChanged("スレッド作成日");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string スレッド名 {
            get {
                return this.スレッド名Field;
            }
            set {
                if ((object.ReferenceEquals(this.スレッド名Field, value) != true)) {
                    this.スレッド名Field = value;
                    this.RaisePropertyChanged("スレッド名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 画像パス {
            get {
                return this.画像パスField;
            }
            set {
                if ((object.ReferenceEquals(this.画像パスField, value) != true)) {
                    this.画像パスField = value;
                    this.RaisePropertyChanged("画像パス");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="テロップ記事リターンEntity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class テロップ記事リターンEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string テロップ記事Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 読み込み成功かField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string テロップ記事 {
            get {
                return this.テロップ記事Field;
            }
            set {
                if ((object.ReferenceEquals(this.テロップ記事Field, value) != true)) {
                    this.テロップ記事Field = value;
                    this.RaisePropertyChanged("テロップ記事");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 読み込み成功か {
            get {
                return this.読み込み成功かField;
            }
            set {
                if ((this.読み込み成功かField.Equals(value) != true)) {
                    this.読み込み成功かField = value;
                    this.RaisePropertyChanged("読み込み成功か");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MergeType", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    public enum MergeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        現在庫 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        使用量 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        不動品 = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="在庫MergeリターンEntity", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 在庫MergeリターンEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Merge成功かField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Merge成功か {
            get {
                return this.Merge成功かField;
            }
            set {
                if ((this.Merge成功かField.Equals(value) != true)) {
                    this.Merge成功かField = value;
                    this.RaisePropertyChanged("Merge成功か");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="最終更新日時リターンデータセット", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.File.Reader")]
    [System.SerializableAttribute()]
    public partial class 最終更新日時リターンデータセット : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MEDIS最終更新日時Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool データ取得成功かField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MEDIS最終更新日時 {
            get {
                return this.MEDIS最終更新日時Field;
            }
            set {
                if ((object.ReferenceEquals(this.MEDIS最終更新日時Field, value) != true)) {
                    this.MEDIS最終更新日時Field = value;
                    this.RaisePropertyChanged("MEDIS最終更新日時");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool データ取得成功か {
            get {
                return this.データ取得成功かField;
            }
            set {
                if ((this.データ取得成功かField.Equals(value) != true)) {
                    this.データ取得成功かField = value;
                    this.RaisePropertyChanged("データ取得成功か");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.File.Reader.IFileReader")]
    public interface IFileReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/OpenCSV", ReplyAction="http://tempuri.org/IFileReader/OpenCSVResponse")]
        PharmacyToolMobile.Service.File.Reader.現在庫データ[] OpenCSV(string Filepath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Open使用量CSV", ReplyAction="http://tempuri.org/IFileReader/Open使用量CSVResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf薬局使用量データZYtYGqK_P Open使用量CSV(string 検索文字列, bool 全期間, int 期限加算月);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Open使用量2CSV", ReplyAction="http://tempuri.org/IFileReader/Open使用量2CSVResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf薬局使用量データZYtYGqK_P Open使用量2CSV(string 検索文字列, bool 全期間, int 期限加算月);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Open不動品CSV", ReplyAction="http://tempuri.org/IFileReader/Open不動品CSVResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf不動品データZYtYGqK_P Open不動品CSV(string 検索文字列, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Get現在庫検索データ", ReplyAction="http://tempuri.org/IFileReader/Get現在庫検索データResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf現在庫データZYtYGqK_P Get現在庫検索データ(string 検索ワード, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Get後発品検索データ", ReplyAction="http://tempuri.org/IFileReader/Get後発品検索データResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf現在庫データZYtYGqK_P Get後発品検索データ(string YJコード, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月, [System.ServiceModel.MessageParameterAttribute(Name="他規格_x30FB_剤形も表示する")] bool 他規格剤形も表示する);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Open掲示板データ", ReplyAction="http://tempuri.org/IFileReader/Open掲示板データResponse")]
        PharmacyToolMobile.Service.File.Reader.掲示板リターンデータセット Open掲示板データ(string カテゴリ名, int グループNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/Open掲示板データキーワード検索", ReplyAction="http://tempuri.org/IFileReader/Open掲示板データキーワード検索Response")]
        PharmacyToolMobile.Service.File.Reader.掲示板リターンデータセット Open掲示板データキーワード検索(string キーワード, string カテゴリ名);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/掲示板記事修正確認チェック", ReplyAction="http://tempuri.org/IFileReader/掲示板記事修正確認チェックResponse")]
        PharmacyToolMobile.Service.File.Reader.掲示板記事修正確認Entity 掲示板記事修正確認チェック(string カテゴリ名, string 記事No, string 暗証キー, bool 管理者か);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/GetThreadTitles", ReplyAction="http://tempuri.org/IFileReader/GetThreadTitlesResponse")]
        PharmacyToolMobile.Service.File.Reader.ThreadTitlesEntity[] GetThreadTitles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/テロップ記事読み込み", ReplyAction="http://tempuri.org/IFileReader/テロップ記事読み込みResponse")]
        PharmacyToolMobile.Service.File.Reader.テロップ記事リターンEntity テロップ記事読み込み();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/DoMerge", ReplyAction="http://tempuri.org/IFileReader/DoMergeResponse")]
        PharmacyToolMobile.Service.File.Reader.在庫MergeリターンEntity DoMerge(PharmacyToolMobile.Service.File.Reader.MergeType タイプ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReader/GetMEDISデータ最終更新日時", ReplyAction="http://tempuri.org/IFileReader/GetMEDISデータ最終更新日時Response")]
        PharmacyToolMobile.Service.File.Reader.最終更新日時リターンデータセット GetMEDISデータ最終更新日時();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileReaderChannel : PharmacyToolMobile.Service.File.Reader.IFileReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReaderClient : System.ServiceModel.ClientBase<PharmacyToolMobile.Service.File.Reader.IFileReader>, PharmacyToolMobile.Service.File.Reader.IFileReader {
        
        public FileReaderClient() {
        }
        
        public FileReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PharmacyToolMobile.Service.File.Reader.現在庫データ[] OpenCSV(string Filepath) {
            return base.Channel.OpenCSV(Filepath);
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf薬局使用量データZYtYGqK_P Open使用量CSV(string 検索文字列, bool 全期間, int 期限加算月) {
            return base.Channel.Open使用量CSV(検索文字列, 全期間, 期限加算月);
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf薬局使用量データZYtYGqK_P Open使用量2CSV(string 検索文字列, bool 全期間, int 期限加算月) {
            return base.Channel.Open使用量2CSV(検索文字列, 全期間, 期限加算月);
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf不動品データZYtYGqK_P Open不動品CSV(string 検索文字列, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月) {
            return base.Channel.Open不動品CSV(検索文字列, 全期限, 期限内, 期限切, 期限指定か, 以内指定か, 期限加算月);
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf現在庫データZYtYGqK_P Get現在庫検索データ(string 検索ワード, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月) {
            return base.Channel.Get現在庫検索データ(検索ワード, 全期限, 期限内, 期限切, 期限指定か, 以内指定か, 期限加算月);
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫リターンデータセットOf現在庫データZYtYGqK_P Get後発品検索データ(string YJコード, bool 全期限, bool 期限内, bool 期限切, bool 期限指定か, bool 以内指定か, int 期限加算月, bool 他規格剤形も表示する) {
            return base.Channel.Get後発品検索データ(YJコード, 全期限, 期限内, 期限切, 期限指定か, 以内指定か, 期限加算月, 他規格剤形も表示する);
        }
        
        public PharmacyToolMobile.Service.File.Reader.掲示板リターンデータセット Open掲示板データ(string カテゴリ名, int グループNo) {
            return base.Channel.Open掲示板データ(カテゴリ名, グループNo);
        }
        
        public PharmacyToolMobile.Service.File.Reader.掲示板リターンデータセット Open掲示板データキーワード検索(string キーワード, string カテゴリ名) {
            return base.Channel.Open掲示板データキーワード検索(キーワード, カテゴリ名);
        }
        
        public PharmacyToolMobile.Service.File.Reader.掲示板記事修正確認Entity 掲示板記事修正確認チェック(string カテゴリ名, string 記事No, string 暗証キー, bool 管理者か) {
            return base.Channel.掲示板記事修正確認チェック(カテゴリ名, 記事No, 暗証キー, 管理者か);
        }
        
        public PharmacyToolMobile.Service.File.Reader.ThreadTitlesEntity[] GetThreadTitles() {
            return base.Channel.GetThreadTitles();
        }
        
        public PharmacyToolMobile.Service.File.Reader.テロップ記事リターンEntity テロップ記事読み込み() {
            return base.Channel.テロップ記事読み込み();
        }
        
        public PharmacyToolMobile.Service.File.Reader.在庫MergeリターンEntity DoMerge(PharmacyToolMobile.Service.File.Reader.MergeType タイプ) {
            return base.Channel.DoMerge(タイプ);
        }
        
        public PharmacyToolMobile.Service.File.Reader.最終更新日時リターンデータセット GetMEDISデータ最終更新日時() {
            return base.Channel.GetMEDISデータ最終更新日時();
        }
    }
}
