//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.225
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyToolMobile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\掲示板資料\\")]
        public string Upload掲示板FileRootPathNAKAYAMA {
            get {
                return ((string)(this["Upload掲示板FileRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\掲示板\\")]
        public string 掲示板データRootPathNAKAYAMA {
            get {
                return ((string)(this["掲示板データRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\掲示板\\")]
        public string 掲示板データRootPathDEBUG {
            get {
                return ((string)(this["掲示板データRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\掲示板資料\\")]
        public string Upload掲示板FileRootPathDEBUG {
            get {
                return ((string)(this["Upload掲示板FileRootPathDEBUG"]));
            }
        }
    }
}
