//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="アクセス数取得結果", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.DAO.PharmacyTool" +
        ".%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E6%95%B0%E7%AE%A1%E7%90%86")]
    [System.SerializableAttribute()]
    public partial class アクセス数取得結果 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int アクセス数Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string エラーメッセージField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 取得成功かField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int アクセス数 {
            get {
                return this.アクセス数Field;
            }
            set {
                if ((this.アクセス数Field.Equals(value) != true)) {
                    this.アクセス数Field = value;
                    this.RaisePropertyChanged("アクセス数");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string エラーメッセージ {
            get {
                return this.エラーメッセージField;
            }
            set {
                if ((object.ReferenceEquals(this.エラーメッセージField, value) != true)) {
                    this.エラーメッセージField = value;
                    this.RaisePropertyChanged("エラーメッセージ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 取得成功か {
            get {
                return this.取得成功かField;
            }
            set {
                if ((this.取得成功かField.Equals(value) != true)) {
                    this.取得成功かField = value;
                    this.RaisePropertyChanged("取得成功か");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.DAO.PharmacyTool.アクセス数管理.IAccessManagement")]
    public interface IAccessManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessManagement/Doアクセス数カウントアップ取得", ReplyAction="http://tempuri.org/IAccessManagement/Doアクセス数カウントアップ取得Response")]
        PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理.アクセス数取得結果 Doアクセス数カウントアップ取得();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessManagementChannel : PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理.IAccessManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessManagementClient : System.ServiceModel.ClientBase<PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理.IAccessManagement>, PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理.IAccessManagement {
        
        public AccessManagementClient() {
        }
        
        public AccessManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PharmacyToolMobile.Service.DAO.PharmacyTool.アクセス数管理.アクセス数取得結果 Doアクセス数カウントアップ取得() {
            return base.Channel.Doアクセス数カウントアップ取得();
        }
    }
}
