//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace クスリのナカヤマ薬局ツール.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\在庫HP更新ツール\\Update")]
        public string UpdateLocalFolder {
            get {
                return ((string)(this["UpdateLocalFolder"]));
            }
            set {
                this["UpdateLocalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\在庫HP更新ツール\\Version.dat")]
        public string VersionDatLocalPath {
            get {
                return ((string)(this["VersionDatLocalPath"]));
            }
            set {
                this["VersionDatLocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/Update/在庫HP更新ツール")]
        public string UpdateFolderServerPath {
            get {
                return ((string)(this["UpdateFolderServerPath"]));
            }
            set {
                this["UpdateFolderServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/Update/在庫HP更新ツール/Version.dat")]
        public string VersionDatServerPath {
            get {
                return ((string)(this["VersionDatServerPath"]));
            }
            set {
                this["VersionDatServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\在庫HP更新ツール")]
        public string 在庫HP更新ツールRootPath {
            get {
                return ((string)(this["在庫HP更新ツールRootPath"]));
            }
            set {
                this["在庫HP更新ツールRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\在庫HP更新ツールBkUp")]
        public string 在庫HP更新ツールBackUpPath {
            get {
                return ((string)(this["在庫HP更新ツールBackUpPath"]));
            }
            set {
                this["在庫HP更新ツールBackUpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\在庫HP更新ツール\\Settings.ini")]
        public string SettingsIniLocalPath {
            get {
                return ((string)(this["SettingsIniLocalPath"]));
            }
            set {
                this["SettingsIniLocalPath"] = value;
            }
        }
    }
}
