//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyTool.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\")]
        public string ServiceRootPath {
            get {
                return ((string)(this["ServiceRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\資料\\")]
        public string UploadFileRootPathDEBUG {
            get {
                return ((string)(this["UploadFileRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\資料\\")]
        public string UploadFileRootPath {
            get {
                return ((string)(this["UploadFileRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\在庫関連\\")]
        public string 在庫データUploadFileRootPath {
            get {
                return ((string)(this["在庫データUploadFileRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\在庫関連\\")]
        public string 在庫データUploadFileRootPathDEBUG {
            get {
                return ((string)(this["在庫データUploadFileRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\掲示板\\")]
        public string 掲示板データRootPath {
            get {
                return ((string)(this["掲示板データRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\掲示板\\")]
        public string 掲示板データRootPathDEBUG {
            get {
                return ((string)(this["掲示板データRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\掲示板資料\\")]
        public string Upload掲示板FileRootPath {
            get {
                return ((string)(this["Upload掲示板FileRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\掲示板資料\\")]
        public string Upload掲示板FileRootPathDEBUG {
            get {
                return ((string)(this["Upload掲示板FileRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.my-world.me/")]
        public string ServerHttpRoot {
            get {
                return ((string)(this["ServerHttpRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=PharmacyTool;Integrated Security=True")]
        public string DataSourceDEBUG {
            get {
                return ((string)(this["DataSourceDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\在庫関連\\MEDIS\\MEDIS.TX" +
            "T")]
        public string MEDISFilePath {
            get {
                return ((string)(this["MEDISFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\在庫関連\\MEDIS\\MEDIS.TXT")]
        public string MEDISFilePathDEBUG {
            get {
                return ((string)(this["MEDISFilePathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\テロップ\\Terop.dat")]
        public string TeropFilePath {
            get {
                return ((string)(this["TeropFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\テロップ\\Terop.dat")]
        public string TeropFilePathDEBUG {
            get {
                return ((string)(this["TeropFilePathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\my-world.me\\httpdocs\\PharmacyTool\\ClientBin\\テロップ\\")]
        public string TeropRootPath {
            get {
                return ((string)(this["TeropRootPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PharmacyTools\\ClientBin\\テロップ\\")]
        public string TeropRootPathDEBUG {
            get {
                return ((string)(this["TeropRootPathDEBUG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\")]
        public string ServiceRootPathNAKAYAMA {
            get {
                return ((string)(this["ServiceRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\資料\\")]
        public string UploadFileRootPathNAKAYAMA {
            get {
                return ((string)(this["UploadFileRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\在庫関連\\")]
        public string 在庫データUploadFileRootPathNAKAYAMA {
            get {
                return ((string)(this["在庫データUploadFileRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\掲示板資料\\")]
        public string Upload掲示板FileRootPathNAKAYAMA {
            get {
                return ((string)(this["Upload掲示板FileRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.kusurinonakayama.jp/")]
        public string ServerHttpRootNAKAYAMA {
            get {
                return ((string)(this["ServerHttpRootNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\在庫関連\\MEDIS\\" +
            "MEDIS.TXT")]
        public string MEDISFilePathNAKAYAMA {
            get {
                return ((string)(this["MEDISFilePathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\テロップ\\Terop." +
            "dat")]
        public string TeropFilePathNAKAYAMA {
            get {
                return ((string)(this["TeropFilePathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\掲示板\\")]
        public string 掲示板データRootPathNAKAYAMA {
            get {
                return ((string)(this["掲示板データRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\ClientBin\\テロップ\\")]
        public string TeropRootPathNAKAYAMA {
            get {
                return ((string)(this["TeropRootPathNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=dwprdb01.dataweb.ne.jp;User ID=PTAdmin_NAKAYAMA;Password=nakayama01\\$;Init" +
            "ial Catalog=PharmacyTool_NAKAYAMA")]
        public string DataSourceNAKAYAMA {
            get {
                return ((string)(this["DataSourceNAKAYAMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=dwprdb01.dataweb.ne.jp;User ID=PTAdmin;Password=s3cure\\$;Initial Catalog=P" +
            "harmacyTool")]
        public string DataSource {
            get {
                return ((string)(this["DataSource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\inetpub\\vhosts\\kusurinonakayama.jp\\httpdocs\\PharmacyTool\\Service")]
        public string SVCFolderPathNAKAYAMA {
            get {
                return ((string)(this["SVCFolderPathNAKAYAMA"]));
            }
        }
    }
}
