//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyToolMobile.Service.DAO.PharmacyTool.店舗 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PT店舗名リターンデータセット", Namespace="http://schemas.datacontract.org/2004/07/PharmacyTool.Web.Service.DAO.PharmacyTool" +
        ".%E5%BA%97%E8%88%97")]
    [System.SerializableAttribute()]
    public partial class PT店舗名リターンデータセット : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 店舗名Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 店舗名 {
            get {
                return this.店舗名Field;
            }
            set {
                if ((object.ReferenceEquals(this.店舗名Field, value) != true)) {
                    this.店舗名Field = value;
                    this.RaisePropertyChanged("店舗名");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.DAO.PharmacyTool.店舗.IStoreData")]
    public interface IStoreData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreData/店舗名取得", ReplyAction="http://tempuri.org/IStoreData/店舗名取得Response")]
        PharmacyToolMobile.Service.DAO.PharmacyTool.店舗.PT店舗名リターンデータセット[] 店舗名取得();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreData/新規店舗名作成", ReplyAction="http://tempuri.org/IStoreData/新規店舗名作成Response")]
        string 新規店舗名作成(string 作成店舗名);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreData/店舗名削除", ReplyAction="http://tempuri.org/IStoreData/店舗名削除Response")]
        string 店舗名削除(string 削除店舗名);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreDataChannel : PharmacyToolMobile.Service.DAO.PharmacyTool.店舗.IStoreData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreDataClient : System.ServiceModel.ClientBase<PharmacyToolMobile.Service.DAO.PharmacyTool.店舗.IStoreData>, PharmacyToolMobile.Service.DAO.PharmacyTool.店舗.IStoreData {
        
        public StoreDataClient() {
        }
        
        public StoreDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PharmacyToolMobile.Service.DAO.PharmacyTool.店舗.PT店舗名リターンデータセット[] 店舗名取得() {
            return base.Channel.店舗名取得();
        }
        
        public string 新規店舗名作成(string 作成店舗名) {
            return base.Channel.新規店舗名作成(作成店舗名);
        }
        
        public string 店舗名削除(string 削除店舗名) {
            return base.Channel.店舗名削除(削除店舗名);
        }
    }
}
