//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles")]
        public string DownloadFilesPath {
            get {
                return ((string)(this["DownloadFilesPath"]));
            }
            set {
                this["DownloadFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\不動品total.csv")]
        public string Download不動品TotalFilePath {
            get {
                return ((string)(this["Download不動品TotalFilePath"]));
            }
            set {
                this["Download不動品TotalFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\現在庫total.csv")]
        public string Download現在庫TotalFilePath {
            get {
                return ((string)(this["Download現在庫TotalFilePath"]));
            }
            set {
                this["Download現在庫TotalFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\MEDIS_HOT13.TXT")]
        public string DownloadMEDIS_HOT13lFilePath {
            get {
                return ((string)(this["DownloadMEDIS_HOT13lFilePath"]));
            }
            set {
                this["DownloadMEDIS_HOT13lFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\帳合先マスタ.csv")]
        public string Download帳合先マスタFilePath {
            get {
                return ((string)(this["Download帳合先マスタFilePath"]));
            }
            set {
                this["Download帳合先マスタFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\帳合先チェックマスタ医薬品別.csv")]
        public string Download帳合先チェックマスタ医薬品別FilePath {
            get {
                return ((string)(this["Download帳合先チェックマスタ医薬品別FilePath"]));
            }
            set {
                this["Download帳合先チェックマスタ医薬品別FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\個別管理医薬品マスタ.csv")]
        public string Download個別管理医薬品マスタFilePath {
            get {
                return ((string)(this["Download個別管理医薬品マスタFilePath"]));
            }
            set {
                this["Download個別管理医薬品マスタFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MEDICODE DATA\\SEND01.DAT")]
        public string SENDO1DATFilePath {
            get {
                return ((string)(this["SENDO1DATFilePath"]));
            }
            set {
                this["SENDO1DATFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\Settings.ini")]
        public string SettingsIniFilePath {
            get {
                return ((string)(this["SettingsIniFilePath"]));
            }
            set {
                this["SettingsIniFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\OrderLogs")]
        public string OrderLogsFolderPath {
            get {
                return ((string)(this["OrderLogsFolderPath"]));
            }
            set {
                this["OrderLogsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles")]
        public string TempFilesFolderPath {
            get {
                return ((string)(this["TempFilesFolderPath"]));
            }
            set {
                this["TempFilesFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\帳合先マスタTemp.csv")]
        public string TempBlancingAccountsFilePath {
            get {
                return ((string)(this["TempBlancingAccountsFilePath"]));
            }
            set {
                this["TempBlancingAccountsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/帳合先マスタ." +
            "csv")]
        public string UploadPath帳合先マスタCSV {
            get {
                return ((string)(this["UploadPath帳合先マスタCSV"]));
            }
            set {
                this["UploadPath帳合先マスタCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/帳合先チェック" +
            "マスタ医薬品別.csv")]
        public string UploadPath帳合先チェックマスタ医薬品別CSV {
            get {
                return ((string)(this["UploadPath帳合先チェックマスタ医薬品別CSV"]));
            }
            set {
                this["UploadPath帳合先チェックマスタ医薬品別CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/個別管理医薬品" +
            "マスタ.csv")]
        public string UploadPath個別管理医薬品マスタCSV {
            get {
                return ((string)(this["UploadPath個別管理医薬品マスタCSV"]));
            }
            set {
                this["UploadPath個別管理医薬品マスタCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\個別管理医薬品マスタTemp.csv")]
        public string TempIndividualBasedMedicineFilePath {
            get {
                return ((string)(this["TempIndividualBasedMedicineFilePath"]));
            }
            set {
                this["TempIndividualBasedMedicineFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\帳合先チェックマスタメーカー別.csv")]
        public string Download帳合先チェックマスタメーカー別FilePath {
            get {
                return ((string)(this["Download帳合先チェックマスタメーカー別FilePath"]));
            }
            set {
                this["Download帳合先チェックマスタメーカー別FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/帳合先チェック" +
            "マスタメーカー別.csv")]
        public string UploadPath帳合先チェックマスタメーカー別CSV {
            get {
                return ((string)(this["UploadPath帳合先チェックマスタメーカー別CSV"]));
            }
            set {
                this["UploadPath帳合先チェックマスタメーカー別CSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\帳合先チェックマスタメーカー別Temp.csv")]
        public string TempBalancingAccountsCheckMakerSortFilePath {
            get {
                return ((string)(this["TempBalancingAccountsCheckMakerSortFilePath"]));
            }
            set {
                this["TempBalancingAccountsCheckMakerSortFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\帳合先チェックマスタ医薬品別Temp.csv")]
        public string TempBalancingAccountsCheckMedicineSortFilePath {
            get {
                return ((string)(this["TempBalancingAccountsCheckMedicineSortFilePath"]));
            }
            set {
                this["TempBalancingAccountsCheckMedicineSortFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem")]
        public string OASystemRootPath {
            get {
                return ((string)(this["OASystemRootPath"]));
            }
            set {
                this["OASystemRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FESTA")]
        public string MediWebProcessName {
            get {
                return ((string)(this["MediWebProcessName"]));
            }
            set {
                this["MediWebProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MEDICODE-Web SR\\FESTA.exe")]
        public string MediWebProgramPath {
            get {
                return ((string)(this["MediWebProgramPath"]));
            }
            set {
                this["MediWebProgramPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OASystem.exe")]
        public string OASystemProcessName {
            get {
                return ((string)(this["OASystemProcessName"]));
            }
            set {
                this["OASystemProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/Update/OASystem/Version.dat")]
        public string VersionDatServerPath {
            get {
                return ((string)(this["VersionDatServerPath"]));
            }
            set {
                this["VersionDatServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/Update/OASystem")]
        public string UpdateFolderServerPath {
            get {
                return ((string)(this["UpdateFolderServerPath"]));
            }
            set {
                this["UpdateFolderServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\Update")]
        public string UpdateLocalFolder {
            get {
                return ((string)(this["UpdateLocalFolder"]));
            }
            set {
                this["UpdateLocalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\Version.dat")]
        public string VersionDatLocalPath {
            get {
                return ((string)(this["VersionDatLocalPath"]));
            }
            set {
                this["VersionDatLocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystemBkUp")]
        public string OASystemBackUpPath {
            get {
                return ((string)(this["OASystemBackUpPath"]));
            }
            set {
                this["OASystemBackUpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/在庫関連/MEDIS/MEDIS_HO" +
            "T13.TXT")]
        public string UploadMEDIS_HOT13FilePath {
            get {
                return ((string)(this["UploadMEDIS_HOT13FilePath"]));
            }
            set {
                this["UploadMEDIS_HOT13FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\保護リストTemp.csv")]
        public string Temp保護リストFilePath {
            get {
                return ((string)(this["Temp保護リストFilePath"]));
            }
            set {
                this["Temp保護リストFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/保護リスト")]
        public string UploadFolderPath保護リスト {
            get {
                return ((string)(this["UploadFolderPath保護リスト"]));
            }
            set {
                this["UploadFolderPath保護リスト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\TempFiles\\優先移動リストTemp.csv")]
        public string Temp優先移動リストFilePath {
            get {
                return ((string)(this["Temp優先移動リストFilePath"]));
            }
            set {
                this["Temp優先移動リストFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.kusurinonakayama.jp/httpdocs/PharmacyTool/ClientBin/発注支援システムマスタ/優先移動リスト" +
            "")]
        public string UploadFolderPath優先移動リスト {
            get {
                return ((string)(this["UploadFolderPath優先移動リスト"]));
            }
            set {
                this["UploadFolderPath優先移動リスト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\保護リスト")]
        public string Download保護リストFolderPath {
            get {
                return ((string)(this["Download保護リストFolderPath"]));
            }
            set {
                this["Download保護リストFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\OASystem\\DownloadFiles\\優先移動リスト")]
        public string Download優先移動リストFolderPath {
            get {
                return ((string)(this["Download優先移動リストFolderPath"]));
            }
            set {
                this["Download優先移動リストFolderPath"] = value;
            }
        }
    }
}
